// ================================================================
//  SA_NxN_top — Pure Datapath Tile  (no internal control unit)
//
//  SA_CU has been removed. Control signals (load_w, valid_out,
//  busy) are now generated by Lego_CU and applied to all four
//  tiles simultaneously from outside.
//
//  This module is a structural wrapper for:
//    ① TRSRL   — activation skew  (delay act_in[row] by row cycles)
//    ② SA_NxN  — N×N systolic array (weight-stationary)
//    ③ TRSDL   — output de-skew   (align psum columns in time)
//
//  ── Port changes from old version ──────────────────────────────
//
//    REMOVED  valid_in  — no longer needed (CU gone)
//    REMOVED  valid_out — generated by Lego_CU, not here
//    REMOVED  busy      — generated by Lego_CU, not here
//    ADDED    load_w    — driven by Lego_CU directly
//
//  ── Parameters ─────────────────────────────────────────────────
//
//    DATA_W     : activation / weight bit-width  (default 8)
//    DATA_W_OUT : accumulator bit-width          (default 32)
//    N_SIZE     : tile dimension                 (default 16)
//
//  ── Timing (controlled externally by Lego_CU) ──────────────────
//
//    LOAD_W : N_SIZE cycles  load_w=1   → PEs latch weight_in
//    FEED_A : N_SIZE cycles  load_w=0   → PEs accumulate act×weight
//    DRAIN  : N_SIZE-1 cycles            → TRSDL shifts out psums
//    OUTPUT : N_SIZE cycles              → psum_out valid per cycle
//
// ================================================================

module L_SA_NxN_top #(
    parameter DATA_W     = 8 ,
    parameter DATA_W_OUT = 32,
    parameter N_SIZE     = 16
)(
    input  logic                     clk          ,
    input  logic                     rst_n        ,

    // ── Data inputs ────────────────────────────────────────────
    input  logic [DATA_W-1:0]        act_in    [N_SIZE],
    input  logic [DATA_W-1:0]        weight_in [N_SIZE],
    input  logic                     transpose_en      ,

    // ── Control input (from Lego_CU) ───────────────────────────
    input  logic                     load_w            ,    // weight-latch enable

    // ── Output ─────────────────────────────────────────────────
    output logic [DATA_W_OUT-1:0]    psum_out  [N_SIZE]
);

// ── Internal wires ─────────────────────────────────────────────
logic [DATA_W-1:0]     act_skewed  [N_SIZE];
logic [DATA_W_OUT-1:0] psum        [N_SIZE];
logic [DATA_W_OUT-1:0] psum_to_dl  [N_SIZE];
logic [DATA_W_OUT-1:0] psum_dl     [N_SIZE];

// ================================================================
//  ① Activation skew — TRSRL
//     act_in[row] is delayed by `row` cycles so that all activations
//     arrive at their correct diagonal in the systolic array.
// ================================================================
TRSRL #(
    .DATAWIDTH (DATA_W ),
    .N_SIZE    (N_SIZE )
) u_trsrl (
    .clk    (clk       ),
    .rst_n  (rst_n     ),
    .act_in (act_in    ),
    .act_out(act_skewed)
);

// ================================================================
//  ② N_SIZE × N_SIZE Systolic Array
//     Weight-stationary: PEs latch weight_in when load_w=1.
//     PEs accumulate when load_w=0.
// ================================================================
SA_NxN #(
    .DATA_W    (DATA_W    ),
    .DATA_W_OUT(DATA_W_OUT),
    .N_SIZE    (N_SIZE    )
) u_sa (
    .clk         (clk         ),
    .rst_n       (rst_n       ),
    .act_in      (act_skewed  ),
    .weight_in   (weight_in   ),
    .load_w      (load_w      ),
    .transpose_en(transpose_en),
    .psum_out    (psum        )
);

// ================================================================
//  ③ Output de-skew — TRSDL
//     The SA produces psum[col] one cycle later per column (diagonal
//     skew from the TRSRL input). TRSDL reverses this skew so that
//     all N output values for one activation row appear simultaneously.
//
//     Reorder before TRSDL: psum_to_dl[i] = psum[N_SIZE-1-i]
//     Reorder after  TRSDL: psum_out[i]   = psum_dl[N_SIZE-1-i]
// ================================================================
genvar i;
generate
    for (i = 0; i < N_SIZE; i++) begin : REORDER
        assign psum_to_dl[i] = psum[N_SIZE-1-i];
        assign psum_out[i]   = psum_dl[N_SIZE-1-i];
    end
endgenerate

TRSDL #(
    .DATAWIDTH (DATA_W_OUT),
    .N_SIZE    (N_SIZE    )
) u_trsdl (
    .clk     (clk       ),
    .rst_n   (rst_n     ),
    .psum_in (psum_to_dl),
    .psum_out(psum_dl   )
);

endmodule